[build]
publish = "dist"
command = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
source $HOME/.cargo/env && \
cargo install trunk && \
trunk build --release"""

[build.environment]
RUSTUP_TOOLCHAIN = "stable" 